git remote add Maxim0382                 https://github.com/Maxim0382/spbetu_comparch_2021_0382.git         # Азаров
git remote add Hedy-dev                  https://github.com/Hedy-dev/spbetu_comparch_2021_0382.git          # Андрющенко      
git remote add HoshiyamaSeizen           https://github.com/HoshiyamaSeizen/spbetu_comparch_2021_0382.git   # Афанасьев
git remote add ngudow                    https://github.com/ngudow/spbetu_comparch_2021_0382.git            # Гудов
git remote add detkovaannya              https://github.com/detkovaannya/spbetu_comparch_2021_0382.git      # Деткова 
git remote add DanilFlint                https://github.com/DanilFlint/spbetu_comparch_2021_0382.git        # Диденко           
git remote add Khail909                  https://github.com/Khail909/spbetu_comparch_2021_0382.git          # Довченкоo       
git remote add velonzy                   https://github.com/velonzy/spbetu_comparch_2021_0382.git           # Здобнова       
git remote add Andrew-Zlobin             https://github.com/Andrew-Zlobin/spbetu_comparch_2021_0382.git     # Злобин 
git remote add Fittern                   https://github.com/Fittern/spbetu_comparch_2021_0382.git           # Ильин          
git remote add YuriiKondratov            https://github.com/YuriiKondratov/spbetu_comparch_2021_0382.git    # Кондратов 
git remote add Lyubava0382               https://github.com/Lyubava0382/spbetu_comparch_2021_0382.git       # Кривенцова
git remote add Mathless                  https://github.com/Mathless/spbetu_comparch_2021_0382.git          # Крючков         
git remote add kulikov02                 https://github.com/kulikov02/spbetu_comparch_2021_0382.git         # Куликов          
git remote add SemyonLityagin            https://github.com/SemyonLityagin/spbetu_comparch_2021_0382.git    # Литягин 
git remote add oksi-oksik                https://github.com/oksi-oksik/spbetu_comparch_2021_0382.git        # Михайлова         
git remote add FavoriteCoffee            https://github.com/FavoriteCoffee/spbetu_comparch_2021_0382.git    # Морева   
git remote add ev-osi                    https://github.com/ev-osi/spbetu_comparch_2021_0382.git            # Осинкин       
git remote add galinaOkhotnikova         https://github.com/galinaOkhotnikova/spbetu_comparch_2021_0382.git # Охотникова
git remote add ranatasha                 https://github.com/ranatasha/spbetu_comparch_2021_0382.git         # Рубежова         
git remote add Vadsxd                    https://github.com/Vadsxd/spbetu_comparch_2021_0382.git            # Санников      
git remote add vasilysamulevich          https://github.com/vasilysamulevich/spbetu_comparch_2021_0382.git  # Самулевич 
git remote add DmitrySergeev02           https://github.com/DmitrySergeev02/spbetu_comparch_2021_0382.git   # Сергеев  
git remote add Sergei4302                https://github.com/Sergei4302/spbetu_comparch_2021_0382.git        # Тихонов           
git remote add Timofey02                 https://github.com/Timofey02/spbetu_comparch_2021_0382.git         # Тюленев          
git remote add lizavetaChe               https://github.com/lizavetaChe/spbetu_comparch_2021_0382.git       # Чегодаева 
git remote add vasiliy2002               https://github.com/vasiliy2002/spbetu_comparch_2021_0382.git       # Шангичев
#git remote add                           https://github.com//spbetu_comparch_2021_0382.git
